# Based on Night Owlish Light

[colors.primary]
background = '#bababd'
foreground = '#333331'

[colors.normal]
black = '#bababd'
# lazygit:
#   1) the text that has been removed in inspected file 
# yazi:
#   1) the background color of lines an warning or something 
red = '#ff0000'
# lazygit:
#   1) the text color of the files that has been staged files, but currently NOT under the cursor.
#   2) the text color of commits in the Commits pane
# alacritty:
#   1) the text color of the terminal shell, which is super inconvenient if you want it greyscale
green = '#333331'
# lazygit:
#   1) the text color of "Ask Question".
#   2) the text color of "Stage/Unstage" print in Command Log.
#   3) the text marked in search.
#   4) the text color of folders that has files staged but not all of them.
#   5) the text color of uncommitted commits in the Commits pane 
yellow = '#0045a8'
# yazi:
#   1) the main text color in Yazi
#   2) the background color of the outer tab of the status line
#   3) the text color of the itter tab of the status line
blue = '#5f5f5d'
# lazygit:
#   1) the text color of the "Donate" button
magenta = '#333331'
# lazygit:
#   1) the text color of "@@ 9,15 +9,17 @@".
#   2) the text color of "1w" on the left in the Local Branches pane
#   3) the text color of "You can hide/focus this panel..." in Command Log 
cyan = '#000000'
# yazi:
#   1) the backgroud color of the inner "tabs" in the statusline 
white = '#afafaf'

[colors.bright]
# yazi:
#   1) the '-' in 'drwx-----'
black = '#333331'
# lazygit:
#   1) part of the command text in the "upstream reset option" ('g') popup. 
red = '#333331'
# lazygit:
#   1) the text color of the cursor line if it is a staged file AND under the cursor
green = '#333331'
# lazygit:
#   1) the text color of the cursor line if it is a folder and it has a file marked for commit but not all
yellow = '#3388aa'
# unknown
blue = '#ff0000'
# the bindings label in the 'go-to' panel ('g') in Yazi 
magenta = '#787876'
# the key bindings in the 'go-to' panel ('g') in Yazi 
cyan = '#333331'
# unknown
white = '#333331'

[colors.dim]
black = '#333331'
# unknown
red = '#333331'
# unknown
green = '#333331'
# unknown
yellow = '#333331'
# unknown
blue = '#333331'
# unknown
magenta = '#333331'
# unknown
cyan = '#333331'
# unknown
white = '#333331'

[colors.cursor]
cursor = '#3388ea'
text = '#fffffd'

[colors.selection]
background = '#efefed'
text = '#333331'

########### monium_dark palette
# error = "#ff0000"
# warning = "#ffff70"
# hint = "#aa55aa"
# info = "#00ff00"
# red = "#a93636"
# green = "#065905"
# blue = "#6666aa"
# cursor = "#3388ea"


# s9 = "#fffffd"
# s8 = "#fafaf6"
# s7 = "#efefed"
# s6 = "#d2d2d0"
# s5 = "#bababd"
# s4 = "#a1a1a1"
# s3 = "#787876"
# s2 = "#5f5f5d"
# s1 = "#333331"
# s0 = "#000000"
